routes/backend.php
<?php
use Illuminate\Support\Facades\Route;

Route::namespace('Backend')
    ->prefix('admin')->group( function(){
    Route::middleware('administrator.check')
        ->get('/', 'AuthenticationController@showLoginForm')
        ->name('backend.login');

    Route::post('/login', 'AuthenticationController@login')->name('backend.post.login');
    Route::get('/logout', 'AuthenticationController@loggedOut')->name('backend.logout');

    Route::group(['guard' => 'administrator', 'middleware' => 'administrator'],function () {
        Route::group(['prefix' => 'filemanager'], function () {
            Route::get('/', '\UniSharp\LaravelFilemanager\Controllers\LfmController@show')
                ->middleware('can:visible image');
            Route::post('/upload', '\UniSharp\LaravelFilemanager\Controllers\UploadController@upload')
                ->middleware('can:create image');;
        });

        Route::get('/dashboard', 'DashboardController@index')->name('backend.dashboard');
        Route::get('/cache/clear', 'SettingController@clearCache')->name('backend.cache.clear');

        Route::get('/profile', 'ProfileController@index')->name('backend.profile');
        Route::post('/profile/edit', 'ProfileController@edit')->name('backend.profile.edit');

        Route::get('/menu', 'MenuController@index')->name('backend.menu');
        Route::get('/menu/{id}', 'MenuController@detail')->name('backend.menu.detail');
        Route::get('/menu-item/{id}', 'MenuController@detailItem')->name('backend.menuItem.detail');
        Route::post('menu-item/store', 'MenuController@addMenuItem')->name('backend.menuItem.store');
        Route::post('menu-item/update', 'MenuController@updateMenuItem')->name('backend.menuItem.update');
        Route::post('menu-item/update-position', 'MenuController@updateMenuItemPosition')->name('backend.menuItem.updatePosition');
        Route::post('menu-item/delete/{id}', 'MenuController@deleteMenuItem')->name('backend.menuItem.delete');

        Route::get('/setting/general', 'SettingController@index')->name('backend.setting.general');
        Route::get('/setting/cache', 'SettingController@cache')->name('backend.setting.cache');
        Route::post('/setting', 'SettingController@save')->name('backend.setting.save');

        Route::get('media', 'MediaController@index')->name('backend.media');

        Route::resource('comments', 'CommentController');
        Route::post('comments/multiple-destroy', 'CommentController@multipleDestroy')->name('comments.multipleDestroy');

        Route::get('contacts', 'ContactController@index')->name('contacts.index');
        Route::get('contacts/{id}', 'ContactController@show')->name('contacts.show');

        Route::resource('blocks', 'BlockController');
        Route::post('blocks/{id}/duplicate', 'BlockController@duplicate')->name('blocks.duplicate');
        Route::post('blocks/multiple-destroy', 'BlockController@multipleDestroy')->name('blocks.multipleDestroy');

        Route::resource('articles', 'ArticleController');
        Route::post('articles/{id}/duplicate', 'ArticleController@duplicate')->name('articles.duplicate');
        Route::post('articles/multiple-destroy', 'ArticleController@multipleDestroy')->name('articles.multipleDestroy');
        Route::post('articles/update-field/{id}', 'ArticleController@updateField')->name('articles.updateField');

        Route::get('trashed-articles', 'ArticleController@trash')->name('articles.trash');
        Route::post('articles/{id}/restore', 'ArticleController@restore')->name('articles.restore');
        Route::post('articles/multiple-restore-trash', 'ArticleController@multipleRestoreTrash')->name('articles.multipleRestore');
        Route::post('articles/multiple-destroy-trash', 'ArticleController@multipleDestroyTrash')->name('articles.multipleDestroyTrash');
        Route::post('articles/delete-permanently/{id}', 'ArticleController@destroyPermanently')->name('articles.destroyPermanently');

        Route::resource('article-categories', 'ArticleCategoryController');
        Route::post('article-categories/multiple-destroy', 'ArticleCategoryController@multipleDestroy')
            ->name('article-categories.multipleDestroy');

        Route::resource('article-tags', 'ArticleTagController');
        Route::post('article-tags/multiple-destroy', 'ArticleTagController@multipleDestroy')
            ->name('article-tags.multipleDestroy');

        Route::resource('products', 'ProductController');
        Route::post('products/{id}/duplicate', 'ProductController@duplicate')->name('products.duplicate');
        Route::post('products/multiple-destroy', 'ProductController@multipleDestroy')->name('products.multipleDestroy');
        Route::post('products/update-field/{id}', 'ProductController@updateField')->name('products.updateField');

        Route::get('trashed-products', 'ProductController@trash')->name('products.trash');
        Route::post('products/{id}/restore', 'ProductController@restore')->name('products.restore');
        Route::post('products/multiple-restore-trash', 'ProductController@multipleRestoreTrash')->name('products.multipleRestore');
        Route::post('products/multiple-destroy-trash', 'ProductController@multipleDestroyTrash')->name('products.multipleDestroyTrash');
        Route::post('products/delete-permanently/{id}', 'ProductController@destroyPermanently')->name('products.destroyPermanently');

        Route::resource('product-categories', 'ProductCategoryController');
        Route::post('product-categories/multiple-destroy', 'ProductCategoryController@multipleDestroy')
            ->name('product-categories.multipleDestroy');

        Route::resource('pages', 'PageController');
        Route::post('pages/{id}/duplicate', 'PageController@duplicate')->name('pages.duplicate');
        Route::post('pages/multiple-destroy', 'PageController@multipleDestroy')->name('pages.multipleDestroy');

        Route::get('trashed-pages', 'PageController@trash')->name('pages.trash');
        Route::post('pages/{id}/restore', 'PageController@restore')->name('pages.restore');
        Route::post('pages/multiple-restore-trash', 'PageController@multipleRestoreTrash')->name('pages.multipleRestore');
        Route::post('pages/multiple-destroy-trash', 'PageController@multipleDestroyTrash')->name('pages.multipleDestroyTrash');
        Route::post('pages/delete-permanently/{id}', 'PageController@destroyPermanently')->name('pages.destroyPermanently');

        Route::resource('orders', 'OrderController');
        Route::resource('sliders', 'SliderController');
        Route::post('sliders/update-field/{id}', 'SliderController@updateField')->name('sliders.updateField');
        Route::resource('administrators', 'AdministratorController');
        Route::resource('roles', 'RoleController');
    });

});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::name('frontend.')->group(function(){
    Route::middleware('cacheResponse')->group(function() {
        Route::get('/', 'HomeController@index')->name('home');
        Route::get('tag/{slug}', 'TagController@detail')->name('tag.detail');
        Route::get('lien-he', 'ContactController@index')->name('contact');
        Route::get('tin-tuc', 'ArticleController@index')->name('news');

    });

    Route::post('subscribe', 'HomeController@subscribe')->name('subscribe');
    Route::post('lien-he/store', 'ContactController@store')->name('contact.store');
    Route::post('attachment/upload', 'AttachmentController@upload')->name('attachment.upload');
});

require_once 'backend.php';

app/Http/Controllers/Backend/AdministratorController.php
<?php

namespace App\Http\Controllers\Backend;

use App\DataTables\AdministratorDataTable;
use App\Http\Controllers\Controller;
use App\Models\Administrator;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Role;

class AdministratorController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Administrator::class);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(AdministratorDataTable $dataTable)
    {
        $title = "Danh sách quản trị viên";
        return $dataTable->render('backend.datatable',compact("title"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $roles = Role::orderBy('name')->get();
        return view('backend.administrator.add',compact("roles"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'username' => 'required|unique:administrators',
            'email' => 'required|unique:administrators|email',
            'password' => 'required|min:6',
            'role_id' => 'required',
        ]);

        try{
            DB::beginTransaction();

            $administrator = new Administrator();
            $administrator->name = $request->input('name');
            $administrator->username = $request->input('username');
            $administrator->email = $request->input('email');
            $administrator->password = bcrypt($request->input('password'));
            $administrator->role_id = $request->input('role_id');
            $administrator->avatar = $request->input('avatar');
            $administrator->save();

            $role = Role::findOrFail($request->input('role_id'));
            $administrator->assignRole($role);

            DB::commit();
            return redirect()->route('administrators.index')->with(['success' => 'Thêm quản trị viên thành công.']);
        }catch (\Exception $e){
            DB::rollback();
            return back()->withInput($request->all())->withErrors([$e->getMessage()]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Administrator  $administrator
     * @return \Illuminate\Http\Response
     */
    public function show(Administrator $administrator)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Administrator  $administrator
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Administrator $administrator)
    {
        $roles = Role::orderBy('name')->get();
        return view('backend.administrator.edit',compact("roles", "administrator"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Administrator  $administrator
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, Administrator $administrator)
    {
        $request->validate([
            'name' => 'required',
            'username' => 'required|unique:administrators,username,'.$administrator->id,
            'email' => 'required|email|unique:administrators,email,'.$administrator->id,
            'role_id' => 'required',
        ]);

        try{
            DB::beginTransaction();
            $administrator->name = $request->input('name');
            $administrator->username = $request->input('username');
            $administrator->email = $request->input('email');

            if($request->input('password')){
                $administrator->password = bcrypt($request->input('password'));
            }

            $administrator->role_id = $request->input('role_id');
            $administrator->avatar = $request->input('avatar');
            $administrator->save();

            $role = Role::findOrFail($request->input('role_id'));
            $administrator->assignRole($role);

            DB::commit();
            return back()->with(['success' => 'Chỉnh sửa quản trị viên thành công.']);
        }catch (\Exception $e){
            DB::rollback();
            return back()->withInput($request->all())->withErrors([$e->getMessage()]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Administrator  $administrator
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy(Administrator $administrator)
    {
        if($administrator->id == Auth::guard('administrator')->user()->id){
            return response()->json(['message' => "Không thể xóa bản ghi này."], 422);
        }

        try {
            DB::beginTransaction();
            $administrator->delete();

            DB::commit();
            return response()->json(['success' => true]);
        }catch (\Exception $e){
            DB::rollBack();
            return response()->json(['message' => $e->getMessage()], 422);
        }
    }
}

app/Http/Controllers/Backend/AuthenticationController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Foundation\Auth\AuthenticatesUsers;
use Illuminate\Support\Facades\Auth;

class AuthenticationController extends Controller
{
    use AuthenticatesUsers;

    protected $redirectTo = 'admin/dashboard';

    public function username()
    {
        return 'username';
    }

    protected function guard()
    {
        return Auth::guard('administrator');
    }

    public function showLoginForm(){
        return view('backend.login');
    }

    protected function validateLogin(Request $request)
    {
        $request->validate([
            $this->username() => 'required|string',
            'password' => 'required|string',
        ]);
    }

    protected function loggedOut(Request $request)
    {
        $this->guard()->logout();
        return redirect()->route('backend.login');
    }
}

app/Http/Controllers/Backend/CommentController.php
<?php

namespace App\Http\Controllers\Backend;

use App\DataTables\CommentDataTable;
use App\Http\Controllers\Controller;
use App\Models\Comment;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\DB;

class CommentController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Comment::class);
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index(CommentDataTable $datatable)
    {
        $title = "Danh sách bình luận";
        return $datatable->render('backend.datatable',compact("title"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Comment  $comment
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Comment $comment)
    {
        $comment->load('commentable');
        return view('backend.comment.detail',compact("comment"));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Comment  $comment
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Comment $comment)
    {

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Comment  $comment
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, Comment $comment)
    {

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Comment  $comment
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy(Comment $comment)
    {
        try {
            DB::beginTransaction();
            $comment->delete();
            DB::commit();
            return response()->json(['success' => true]);
        }catch (\Exception $e){
            DB::rollBack();
            return response()->json(['message' => $e->getMessage()], 422);
        }
    }

    public function multipleDestroy(Request $request)
    {
        $ids = $request->input('ids');

        try{
            $this->authorize('delete', Comment::find($ids[0]));

            DB::beginTransaction();

            foreach ($ids as $id){
                $category = Comment::find($id);
                $category->delete();
            }

            DB::commit();
            return response()->json(['success' => true]);
        }catch (\Exception $e){
            DB::rollBack();
            return response()->json(['message' => $e->getMessage()], 422);
        }
    }
}

app/Http/Controllers/Backend/MediaController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class MediaController extends Controller
{
    public function index()
    {
        return view('backend.media');
    }
}

resources/views/backend/block/add.blade.php
@extends('.backend.layout.main')
@section('title', 'Thêm mới block')
@section('content')
    <div class="breadcrumbs ace-save-state" id="breadcrumbs">
        <ul class="breadcrumb">
            <li>
                <i class="ace-icon fa fa-home home-icon"></i>
                <a href="{{route('blocks.index')}}">Danh sách block</a>
            </li>
            <li class="active">Thêm block</li>
        </ul><!-- /.breadcrumb -->
    </div>

    <div class="page-content">

        <div class="page-header">
            <h1>
                Thêm mới block
            </h1>
        </div><!-- /.page-header -->

        <div class="row">
            <div class="col-xs-12">

                <form method="POST" action="{{route('blocks.store')}}">
                    @csrf
                    @if($errors->any())
                        <div class="alert alert-danger">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <i class="fa fa-close"></i>
                            </button>
                            <div class="error-message">
                                @foreach($errors->all() as $error)
                                    <li>{{$error}}</li>
                                @endforeach
                            </div>
                        </div>
                    @endif

                    @if(session('success'))
                        <div class="alert alert-success mb-5 alert-with-icon">
                            <i class="material-icons" data-notify="icon">done</i>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <i class="material-icons">close</i>
                            </button>
                            {{session('success')}}
                        </div>
                    @endif

                    <div class="row">
                        <div class="col-md-8">
                            <div class="widget-box">
                                <div class="card-body">
                                    <div class="widget-main">
                                        <div class="form-group">
                                            <label>Tiêu đề</label>
                                            <input value="{{old('title')}}" type="text" class="form-control" name="title" required>
                                        </div>

                                        <div class="form-group">
                                            <label>Slug</label>
                                            <input value="{{old('slug')}}" type="text" name="slug" class="form-control">
                                            <small class="form-text text-muted">Để trống nếu muốn sinh tự động.</small>
                                        </div>

                                        <div class="editor-group">
                                            <label>Nội dung</label>
                                            <textarea id="editor" name="content" >{{old('content')}}</textarea>
                                        </div>


                                    </div>

                                </div>
                                <!-- end content-->
                            </div>

                        </div>

                        <div class="col-md-4">
                            <div class="widget-box">
                                <div class="widget-header">
                                    <h4 class="card-title">Nhóm & Liên kết</h4>
                                </div>

                                <div class="widget-main">
                                    <div class="form-group">
                                        <label>Liên kết</label>
                                        <input value="{{old('url')}}" type="text" class="form-control" name="url">
                                    </div>

                                    <div class="form-group">
                                        <label>Nhóm</label>
                                        <select class="form-control" name="group">
                                            <option value="">Chọn nhóm block</option>
                                            <option {{old('group') == 'home' ? 'selected' : ''}} value="home">Trang chủ</option>
                                        </select>

                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                    <!--  end card  -->

                    <div class="clearfix form-actions">
                        <div class="col-md-offset-4 col-md-8">
                            <button class="btn btn-info" type="submit">
                                <i class="ace-icon fa fa-check bigger-110"></i>
                                Thêm mới
                            </button>

                            &nbsp; &nbsp; &nbsp;
                            <button class="btn" type="reset">
                                <i class="ace-icon fa fa-undo bigger-110"></i>
                                Reset
                            </button>
                        </div>
                    </div>
                </form>
            </div>

        </div>
    </div>
@endsection

resources/views/backend/block/edit.blade.php
@extends('.backend.layout.main')
@section('title', 'Chỉnh sửa block')
@section('content')
    <div class="breadcrumbs ace-save-state" id="breadcrumbs">
        <ul class="breadcrumb">
            <li>
                <i class="ace-icon fa fa-home home-icon"></i>
                <a href="{{route('blocks.index')}}">Danh sách block</a>
            </li>
            <li class="active">Chỉnh sửa block</li>
        </ul><!-- /.breadcrumb -->
    </div>

    <div class="page-content">

        <div class="page-header">
            <h1>
                Chỉnh sửa block
            </h1>
        </div><!-- /.page-header -->

        <div class="row">
            <div class="col-xs-12">
                <form method="POST" action="{{route('blocks.update', $block->id)}}">
                    @method('PUT')
                    @csrf
                    @if($errors->any())
                        <div class="alert alert-danger">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <i class="fa fa-close"></i>
                            </button>
                            <div class="error-message">
                                @foreach($errors->all() as $error)
                                    <li>{{$error}}</li>
                                @endforeach
                            </div>
                        </div>
                    @endif

                    @if(session('success'))
                        <div class="alert alert-success mb-5 alert-with-icon">
                            <i class="fa fa-check" ></i>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <i class="fa fa-close"></i>
                            </button>
                            {{session('success')}}
                        </div>
                    @endif

                    <div class="row">
                        <div class="col-md-8">
                            <div class="widget-box">
                                <div class="card-body">
                                    <div class="widget-main">
                                        <div class="form-group">
                                            <label>Tiêu đề</label>
                                            <input value="{{$block->title}}" type="text" class="form-control" name="title" required>
                                        </div>
                                        <div class="form-group">
                                            <label>Slug</label>
                                            <input value="{{$block->slug}}" type="text" name="slug" class="form-control">
                                            <small class="form-text text-muted">Để trống nếu muốn sinh tự động.</small>
                                        </div>

                                        <div class="editor-group">
                                            <label>Nội dung</label>
                                            <textarea id="editor" name="content">{!! $block->content !!}</textarea>
                                        </div>
                                    </div>

                                </div>
                                <!-- end content-->
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="widget-box">
                                <div class="widget-header">
                                    <h4 class="card-title">Nhóm & Liên kết</h4>
                                </div>

                                <div class="widget-main">
                                    <div class="form-group">
                                        <label>Liên kết</label>
                                        <input value="{{$block->url}}" type="text" class="form-control" name="url">
                                    </div>

                                    <div class="form-group">
                                        <label>Nhóm</label>
                                        <select class="form-control" name="group">
                                            <option value="">Chọn nhóm block</option>
                                            <option {{$block->group == 'home' ? 'selected' : ''}} value="home">Trang chủ</option>
                                        </select>
                                    </div>
                                </div>

                            </div>
                        </div>

                    </div>
                    <!--  end card  -->

                    <div class="clearfix form-actions">
                        <div class="col-md-offset-4 col-md-8">
                            <button class="btn btn-info" type="submit">
                                <i class="ace-icon fa fa-check bigger-110"></i>
                                Lưu lại
                            </button>
                            &nbsp; &nbsp; &nbsp;
                            <button class="btn" type="reset">
                                <i class="ace-icon fa fa-undo bigger-110"></i>
                                Reset
                            </button>
                        </div>
                    </div>
                </form>
            </div>

        </div>
    </div>
@endsection